"""VideoWipe - an embeddable video-cleanup engine."""

__version__ = "0.8.2"

from videowipe.api import CancellationToken, ProgressEvent, WipeRequest, WipeResult
from videowipe.detect import (
    CleanCandidate,
    CleanDetectionResult,
    DBNetDetector,
    TextBox,
    TextDetector,
    detect_clean_candidates,
    detect_subtitle_mask,
    infer_regions_from_text,
    infer_targets_from_text,
    mask_from_candidates,
    normalize_region,
    select_candidates_by_intent,
    select_clean_candidates,
)
from videowipe.engine import WipeEngine, remove_text
from videowipe.errors import (
    BackendUnavailableError,
    InvalidInputError,
    ProcessingCancelledError,
    ProcessingError,
    WipeError,
)
from videowipe.inpainters import (
    Inpainter,
    InpaintJob,
    InpaintOutcome,
    STTNInpainter,
    get_registry,
    register_inpainter,
)
from videowipe.plan import (
    MaskAsset,
    Segment,
    Source,
    TemporalResolution,
    Track,
    WipePlan,
    build_wipe_plan,
    compute_source,
    is_temporal,
    load_wipe_plan,
    predicted_mask_at,
    remove_union_mask,
    save_wipe_plan,
    validate_plan,
)

__all__ = [
    "BackendUnavailableError",
    "CancellationToken",
    "CleanCandidate",
    "CleanDetectionResult",
    "DBNetDetector",
    "InpaintJob",
    "InpaintOutcome",
    "Inpainter",
    "InvalidInputError",
    "MaskAsset",
    "ProcessingCancelledError",
    "ProcessingError",
    "ProgressEvent",
    "STTNInpainter",
    "Segment",
    "Source",
    "TemporalResolution",
    "TextBox",
    "TextDetector",
    "Track",
    "WipeEngine",
    "WipeError",
    "WipePlan",
    "WipeRequest",
    "WipeResult",
    "build_wipe_plan",
    "compute_source",
    "detect_clean_candidates",
    "detect_subtitle_mask",
    "get_registry",
    "infer_regions_from_text",
    "infer_targets_from_text",
    "is_temporal",
    "load_wipe_plan",
    "mask_from_candidates",
    "normalize_region",
    "predicted_mask_at",
    "register_inpainter",
    "remove_text",
    "remove_union_mask",
    "save_wipe_plan",
    "select_candidates_by_intent",
    "select_clean_candidates",
    "validate_plan",
]
